# Set the build language to Python
language: python

# Set the python versions
python:
  - "3.8"

addons:
  postgresql: '9.6'
    
# Environment
env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test

# Install pip dependencies
install: pip install -r requirements.txt --use-mirrors

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# Run the unit test
script: python manage.py test

# Deploy to heroku server
# deploy:
#   provider: heroku
#   api_key:
#     secure: HEROKU_API_TOKEN
#   app: immense-cove-99982
#   on:
#     repo:  CHEguK/memorable_places
#     branch: master