# Set the build language to Python
language: python

# Set the python versions
python:
  - "3.8"

# Install pip dependencies
install: pip install --user -r requirements.txt

# Run the unit test
script: python manage.py test

# Deploy to heroku server
# deploy:
#   provider: heroku
#   api_key:
#     secure: HEROKU_API_TOKEN
#   app: immense-cove-99982
#   on:
#     repo:  CHEguK/memorable_places
#     branch: master