# Set the build language to Python
language: python

# Cache to speed up the build
cache: pip

# Set the python versions
python:
  - "3.8"

# Install pip dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# Run the unit test
script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls

Deploy to heroku server
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: immense-cove-99982