# Set the build language to Python
language: python

# Cache to speed up the build
cache: pip

# Set the python versions
python:
  - "3.8"

# Install pip dependencies
install: pip install -r requirements.txt

# Run the unit test
script: python manage.py test

# Deploy to heroku server
deploy:
  provider: heroku
  api_key:
    secure: 31ca72b1-1a1d-445d-a8dc-b4b05b7327b7
  app: 
    master: immense-cove-99982