# Generated by Django 2.2 on 2020-07-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryitem',
            options={'ordering': ('-name',)},
        ),
    ]
