# Generated by Django 2.2 on 2020-07-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20200725_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryitem',
            options={},
        ),
    ]
