# Generated by Django 2.2 on 2020-07-25 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0003_auto_20200725_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryitem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
