# Generated by Django 3.0.8 on 2020-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memoryitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryitem',
            name='coordinates',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
