# Generated by Django 3.0.8 on 2020-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0008_auto_20200804_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryitem',
            name='latitude',
            field=models.CharField(default=56.8444, max_length=64),
        ),
        migrations.AlterField(
            model_name='memoryitem',
            name='longitude',
            field=models.CharField(default=60.60388, max_length=64),
        ),
    ]
